name: DeploytoGitHubPages
on:
 release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create version directory
        run: |
          VERSION=${{ github.event.release.tag_name }}
          
          # Создание директорий для версии
          mkdir -p "./site/${VERSION}/en"
          mkdir -p "./site/${VERSION}/ru"
                
          # Копирование всех файлов и директорий в новую версию
          cp -r ./en/* "./site/${VERSION}/en/"
          cp -r ./ru/* "./site/${VERSION}/ru/"
          cp ./index.html "./site/${VERSION}/"


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          keep_files: true  # Сохранять предыдущие файлы
