name: PagesReleases # Название действия, которое будет выполняться при создании релиза
on:
 release:
    types: [created] # Триггер, который запускает действие при создании нового релиза

jobs:
  deploy: # Определение работы под названием "deploy"
    runs-on: ubuntu-latest # Указание среды выполнения для работы (Ubuntu последней версии)
    steps: # Шаги, которые будут выполнены в рамках работы
    
      - name: Checkout code # 1 Шаг. Извлечение последней версии кода из репозитория
        uses: actions/checkout@v2 

      - name: Build release # 2 Шаг. Создание папок для нового релиза, копирование в нее папок и файлов.
        run: |
          VERSION=${{ github.event.release.tag_name }} # Получение имени тега релиза

          # Создание необходимых папок для релиза
          mkdir -p "./${VERSION}/en/"
          mkdir -p "./${VERSION}/ru/"

          # Копирование всех директорий и файлов в новый релиз
          cp -r ./en/* "./${VERSION}/en/"
          cp -r ./ru/* "./${VERSION}/ru/"
          cp ./index.html "./${VERSION}/"

      - name: Deploy to GitHub Pages # 3 Шаг. Публикация файлов на GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # Используем Actions для публикации
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Токен для аунтефикации
          publish_dir: . # Директория, содержащая файлы для публикации
          publish_branch: gh-pages # Ветка, в которую будут публиковаться файлы
          keep_files: true  # Сохранять предыдущие файлы
