name: DeploytoGitHubPages
on:
 release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create version directory
        run: |
          mkdir -p ./v1
          cp -r ./en ./v1/en
          cp -r ./ru ./v1/ru
          cp ./index.html ./v1/index.html


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./v1
          publish_branch: gh-pages
